// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjbK_GRSajtkehq5qYuJWDuGadp7xebs',
    appId: '1:981635193509:android:ca0fb15a078cac07868b4c',
    messagingSenderId: '981635193509',
    projectId: 'iot-security-cam',
    databaseURL: 'https://iot-security-cam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-security-cam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8pf-m2P5COSgJym0SeUG_cZ3XX0_iSes',
    appId: '1:981635193509:ios:e1fe535d5e2f522a868b4c',
    messagingSenderId: '981635193509',
    projectId: 'iot-security-cam',
    databaseURL: 'https://iot-security-cam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-security-cam.appspot.com',
    iosClientId: '981635193509-2dpi0sso0tlh0qdfgdgk410k4cvbnkio.apps.googleusercontent.com',
    iosBundleId: 'com.torrydo.flutterIotSecurityCam',
  );
}
